version: 2.1

orbs:
  codecov: codecov/codecov@1.1.3

jobs:
  test:
    docker:
      - image: circleci/golang:1.15

    environment:
      PROJECT_DIR: /go/src/github.com/OWASP/Amass

    working_directory: $PROJECT_DIR

    steps:
      - checkout

      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > /go/cc-test-reporter
            chmod +x /go/cc-test-reporter

      - run:
          name: "Amass Unit Tests and Coverage Reports"
          command: |
            cd /go
            go get github.com/OWASP/Amass/v3/...
            cd $PROJECT_DIR
            /go/cc-test-reporter before-build
            go test -coverprofile=c.out -covermode=atomic ./...
            export PREFIX=$(basename $(go list -m))
            /go/cc-test-reporter after-build -r $CODE_CLIMATE_TOKEN -t gocov -p $PREFIX --exit-code $?

      - codecov/upload:
#          conf: $PROJECT_DIR/.codecov.yml
          file: $PROJECT_DIR/c.out

      - run:
          name: Remove Code Climate test-reporter
          command: |
            rm /go/cc-test-reporter

workflows:
  version: 2.1
  main:
    jobs:
      - test
