# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12.3

    working_directory: /go/src/github.com/OWASP/Amass
    steps:
      - checkout
      - run:
          name: "Test Amass"
          command: |
            export GO111MODULE=on
            cd amass
            go test -v -race ./...

  binaries:
    docker:
      - image: circleci/golang:1.12.3

    working_directory: /go/src/github.com/OWASP/Amass
    steps:
      - checkout
      - run:
          name: "Build Amass Binaries"
          command: |
            curl -sL https://git.io/goreleaser | bash

  buildsnap:
    docker:
      - image: snapcore/snapcraft:stable

    working_directory: /go/src/github.com/OWASP/Amass
    steps:
      - checkout

      - run:
          name: "Build Snap Package"
          command: apt update && snapcraft
      - persist_to_workspace:
          root: .
          paths:
            - "*.snap"

  pubsnap:
    docker:
      - image: snapcore/snapcraft:stable
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Publish to Snap Store"
          command: |
            mkdir .snapcraft
            echo $SNAPCRAFT_LOGIN_FILE | base64 --decode --ignore-garbage > .snapcraft/snapcraft.cfg
            snapcraft push *.snap --release edge

workflows:
  version: 2
  main:
    jobs:
      - test
      - binaries:
          requires:
            - test
          filters:
            branches:
              only: master
      - buildsnap:
          requires:
            - test
          filters:
            branches:
              only: master
      - pubsnap:
          requires:
            - buildsnap
          filters:
            branches:
              only: master
